name: Build Nethunter Kernel S20 FE 5G

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - lineage-21
      - master

jobs :
  build:
    runs-on: ubuntu-22.04
    env:
      PATCH_REPO: Linux-on-droid/lindroid-drm-loopback

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v3
    
      - name: Checkout Lindroid DRM Patch
        uses: actions/checkout@v3
        with:
          repository: ${{ env.PATCH_REPO }}
          path: drm-dkms

      - name: Setup Dependencies
        run: |
          sudo apt update -y && sudo apt upgrade -y
          sudo apt install -y \
            nano bc bison ca-certificates curl flex gcc git \
            libc6-dev libssl-dev openssl python-is-python3 ssh wget zip zstd sudo make \
            clang gcc-arm-linux-gnueabi software-properties-common build-essential \
            libarchive-tools gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            libssl-dev libffi-dev libncurses5-dev zlib1g zlib1g-dev \
            libreadline-dev libbz2-dev libsqlite3-dev \
            pigz python2 python3 cpio lld llvm libtinfo5 lz4 neofetch
          
          # cek environment
          neofetch
          # convert Kconfig file biar gak error CRLF
          dos2unix init/Kconfig || true
          dos2unix drivers/perf_mgr/Kconfig || true

      - name: Build Kernel
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Nethunter-Kernel-S20FE5G
          path: artifacts/*
